@echo off
echo StartTime //%time%

echo ...
echo Start to kill existing excel...
@python.exe "00excel_reset.py" %*

echo ...
echo Start to convert xls to xlsx...
@python.exe "01pre_process.py" %*

echo ...
echo Start to inject formula...
@python.exe "02TB_formula.py" %*

echo ...
echo Start to breaklinks of formula...
@python.exe "022formula_pastevalue.py" %*

echo ...
echo Start to combine TB...
@python.exe "03TB_process.py" %*

echo EndTime //%time%

pause