@echo off
echo StartTime //%time%

echo ...
echo Start to kill existing excel...
@python.exe "0001excel_reset.py" %*

echo ...
echo Start to convert xls to xlsx...
@python.exe "0101pre_process.py" %*

echo ...
echo Start to inject formula...
@python.exe "0201TB_formula.py" %*

echo ...
echo Start to breaklinks of formula...
@python.exe "0202formula_pastevalue.py" %*

echo ...
echo Start to combine TB...
@python.exe "0301TB_process.py" %*

echo ...
echo Start to check TB with FS...
@python.exe "0302FS_check.py" %*

echo ...
echo Start to build A3...
@python.exe "0303A3_copy.py" %*

echo ...
echo Start to input adjustments...
@python.exe "0304A3_process.py" %*

echo EndTime //%time%

pause